### ISSUE TITLE
ImportError: cannot import name 'sync' from 'os'

### ISSUE THREAD

**Issue by lxrswdd** [sp-uhh/sgmse#4]
Hi
   I am trying out the enhancement. But the error was raised 

```
Traceback (most recent call last):
  File "D:\A\Pycodes\Speech enhancement and derverberation with diffusion-based generative models\enhancement.py", line 10, in <module>
    from sgmse.model import ScoreModel
  File "D:\A\Pycodes\Speech enhancement and derverberation with diffusion-based generative models\sgmse\model.py", line 1, in <module>
    from os import sync
ImportError: cannot import name 'sync' from 'os' (E:\Anaconda\lib\os.py)
PS D:\A\Pycodes\Speech enhancement and derverberation with diffusion-based generative models>
```

Do you have any idea why?

**Comment by lxrswdd** [comment]
> Hi, this may have to do with a Python version mismatch. We used Python 3.8. However, the problematic import was unused in the first place - I have removed it in this repository just now. Could you try again after pulling the current state of the repo?

Thank you for your reply. I tried python 3.8. It still occurred. 

```

(py38) C:\Users\FunkYou>python "D:\A\Pycodes\Speech enhancement and derverberation with diffusion-based generative models\enhancement.py" --test_dir D:\A\Marine Mammal Detection\datasets\Watkins confused --enhanced_dir D:\A\Marine Mammal Detection\datasets\Watkins confused --ckpt "D:\A\Pycodes\Speech enhancement and derverberation with diffusion-based generative models\checkpoints\train_wsj0_2cta4cov_epoch=159.ckpt"
Traceback (most recent call last):
  File "D:\A\Pycodes\Speech enhancement and derverberation with diffusion-based generative models\enhancement.py", line 10, in <module>
    from sgmse.model import ScoreModel
  File "D:\A\Pycodes\Speech enhancement and derverberation with diffusion-based generative models\sgmse\model.py", line 1, in <module>
    from os import sync
ImportError: cannot import name 'sync' from 'os' (E:\Anaconda\envs\py38\lib\os.py)

(py38) C:\Users\FunkYou>conda env list
# conda environments:
#
base                     E:\Anaconda
myenv                    E:\Anaconda\envs\myenv
py36                     E:\Anaconda\envs\py36
py38                  *  E:\Anaconda\envs\py38


(py38) C:\Users\FunkYou>python
Python 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

```

Anyway, I will try the new repo. Thanks
