### ISSUE TITLE
Always eats up VRAM

### ISSUE THREAD

**Issue by genevera** [sp-uhh/sgmse#55]
I've tried running enhancement.py on a card with 16GB of VRAM and again on another with 48GB of VRAM on different machines and it always OOMs:

```
(sgmse) root@C.13364355:/workspace/sgmse$ python3 ./enhancement.py --ckpt models/train_vb_29nqe0uh_epoch\=115.ckpt --test_dir /workspace/t --enhanced_dir /workspace/enhanced_
dir
Set TORCH_CUDA_ARCH_LIST to: 8.6
  0%|                                                                                                                                                   | 0/2 [00:00<?, ?it/s]
/content/miniconda/envs/sgmse/lib/python3.11/site-packages/torch/nn/modules/conv.py:549: UserWarning: cuDNN cannot be used for large non-batch-splittable convolutions if the
V8 API is not enabled or before cuDNN version 9.3+. Consider upgrading cuDNN and/or enabling the V8 API for better efficiency. (Triggered internally at ../aten/src/ATen/nativ
e/Convolution.cpp:430.)
  return F.conv2d(
  0%|
| 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/sgmse/./enhancement.py", line 93, in <module>
    sample, _ = sampler()
                ^^^^^^^^^
  File "/workspace/sgmse/sgmse/sampling/__init__.py", line 64, in pc_sampler
    xt, xt_mean = corrector.update_fn(xt, y, vec_t)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/sgmse/sgmse/sampling/correctors.py", line 75, in update_fn
    grad = self.score_fn(x, y, t, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/miniconda/envs/sgmse/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/miniconda/envs/sgmse/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/sgmse/sgmse/model.py", line 309, in forward
    score = -self.dnn(dnn_input, t)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/content/miniconda/envs/sgmse/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/miniconda/envs/sgmse/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/sgmse/sgmse/backbones/ncsnpp.py", line 305, in forward
    h = modules[m_idx](hs[-1], temb)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/miniconda/envs/sgmse/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/miniconda/envs/sgmse/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/sgmse/sgmse/backbones/ncsnpp_utils/layerspp.py", line 260, in forward
    h = self.Conv_0(h)
        ^^^^^^^^^^^^^^
  File "/content/miniconda/envs/sgmse/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/miniconda/envs/sgmse/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/miniconda/envs/sgmse/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/miniconda/envs/sgmse/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
           ^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 82.48 GiB. GPU 0 has a total capacity of 44.45 GiB of which 14.88 GiB is free. Process 4068242 has 29.56 GiB mem
ory in use. Of the allocated memory 29.11 GiB is allocated by PyTorch, and 142.42 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try
setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#en
vironment-variables)
```

What am I doing wrong?

**Comment by julius-richter** [comment]
It looks like your GPU is running out of memory, possibly due to the large files you are trying to process. To address this, please try splitting the large files into smaller segments before running the enhancement code.

**Comment by genevera** [comment]
It's a 19M .wav file.  Is that really enough to eat up 48GB of ram?

**Comment by genevera** [comment]
I spoke too soon; evidently it was.  Thank you for setting me straight!
